const extendedMockProductsData = {
  products: [
    // Ropa y Accesorios
    {
      id: 201,
      name: "Sudadera 'Vitra' Edición Limitada",
      description:
        "Cómoda sudadera de algodón orgánico, ideal para cualquier clima. Diseño minimalista.",
      price: 59.99,
      currency: "EUR",
      // URL: Muestra el nombre en un fondo gris suave
      imageUrl:
        "https://placehold.co/400x300/EAEAEA/000000?text=SUDADERA+VITRA",
      category: "Ropa",
      stock: 15,
      rating: 4.5,
      isNew: true,
      isDiscounted: false,
    },
    {
      id: 202,
      name: "Mochila Urbana Antirrobo (Modelo Pro)",
      description:
        "Resistente al agua con compartimento oculto para laptop de 15 pulgadas.",
      price: 65.0,
      currency: "EUR",
      imageUrl:
        "https://placehold.co/400x300/EAEAEA/000000?text=MOCHILA+ANTIRROBO",
      category: "Accesorios",
      stock: 5,
      rating: 4.8,
      isNew: false,
      isDiscounted: true,
      oldPrice: 85.0,
    },
    {
      id: 203,
      name: "Gafas de Sol Polarizadas 'Horizon'",
      description:
        "Montura ligera de bambú con protección UV400. Incluye estuche.",
      price: 29.95,
      currency: "EUR",
      imageUrl: "https://placehold.co/400x300/EAEAEA/000000?text=GAFAS+HORIZON",
      category: "Accesorios",
      stock: 0,
      rating: 4.6,
      isNew: false,
      isDiscounted: false,
    },
    {
      id: 204,
      name: "Zapatillas Deportivas 'Dash' Negras",
      description:
        "Máximo confort y amortiguación. Perfectas para running o uso diario.",
      price: 89.9,
      currency: "EUR",
      imageUrl:
        "https://placehold.co/400x300/EAEAEA/000000?text=ZAPATILLAS+DASH",
      category: "Calzado",
      stock: 95,
      rating: 4.7,
      isNew: true,
      isDiscounted: false,
    },
    // Tecnología
    {
      id: 205,
      name: "Smartwatch Fitness X Pro",
      description:
        "Monitor de ritmo cardíaco, GPS integrado y batería de 10 días.",
      price: 129.0,
      currency: "EUR",
      imageUrl:
        "https://placehold.co/400x300/EAEAEA/000000?text=SMARTWATCH+X+PRO",
      category: "Electrónica",
      stock: 60,
      rating: 4.5,
      isNew: false,
      isDiscounted: false,
    },
    {
      id: 206,
      name: "Teclado Mecánico RGB (Layout ES)",
      description:
        "Switches azules de alta respuesta y retroiluminación personalizable.",
      price: 75.99,
      currency: "EUR",
      imageUrl:
        "https://placehold.co/400x300/EAEAEA/000000?text=TECLADO+MECANICO",
      category: "Electrónica",
      stock: 2,
      rating: 4.9,
      isNew: true,
      isDiscounted: false,
    },
    {
      id: 207,
      name: "Power Bank Ultra Rápida 20000mAh",
      description:
        "Carga dos dispositivos a la vez. Pantalla LED de estado de batería.",
      price: 34.9,
      currency: "EUR",
      imageUrl: "https://placehold.co/400x300/EAEAEA/000000?text=POWER+BANK",
      category: "Electrónica",
      stock: 120,
      rating: 4.1,
      isNew: false,
      isDiscounted: true,
      oldPrice: 45.0,
    },
    {
      id: 208,
      name: "Funda Silicona para Móvil Z-Fold",
      description:
        "Protección premium con tacto suave. Varios colores disponibles.",
      price: 19.99,
      currency: "EUR",
      imageUrl: "https://placehold.co/400x300/EAEAEA/000000?text=FUNDA+Z-FOLD",
      category: "Accesorios",
      stock: 80,
      rating: 4.4,
      isNew: false,
      isDiscounted: false,
    },
    // Hogar y Decoración
    {
      id: 209,
      name: "Set de Velas Aromáticas 'Zen'",
      description:
        "Tres velas de cera de soja con aromas a sándalo, lavanda y té verde.",
      price: 24.5,
      currency: "EUR",
      imageUrl:
        "https://placehold.co/400x300/EAEAEA/000000?text=VELAS+AROMATICAS",
      category: "Hogar",
      stock: 55,
      rating: 4.9,
      isNew: true,
      isDiscounted: false,
    },
    {
      id: 210,
      name: "Manta de Pelo Sintético XL",
      description: "Suavidad inigualable para el sofá o la cama. 180x200 cm.",
      price: 49.99,
      currency: "EUR",
      imageUrl: "https://placehold.co/400x300/EAEAEA/000000?text=MANTA+PELO+XL",
      category: "Hogar",
      stock: 3,
      rating: 4.7,
      isNew: false,
      isDiscounted: false,
    },
    {
      id: 211,
      name: "Difusor de Aromas Ultrasónico",
      description:
        "Silencioso, con luces LED de ambiente y apagado automático.",
      price: 32.75,
      currency: "EUR",
      imageUrl:
        "https://placehold.co/400x300/EAEAEA/000000?text=DIFUSOR+DE+AROMAS",
      category: "Hogar",
      stock: 0,
      rating: 4.5,
      isNew: false,
      isDiscounted: true,
      oldPrice: 40.0,
    },
    {
      id: 212,
      name: "Juego de Utensilios de Bambú (5 piezas)",
      description:
        "Alternativa ecológica y duradera para tu cocina. Diseño ergonómico.",
      price: 18.99,
      currency: "EUR",
      imageUrl:
        "https://placehold.co/400x300/EAEAEA/000000?text=UTENSILIOS+BAMBU",
      category: "Cocina",
      stock: 75,
      rating: 4.2,
      isNew: true,
      isDiscounted: false,
    },
    // Productos de Belleza y Cuidado
    {
      id: 213,
      name: "Crema Facial Hidratante de Noche",
      description: "Fórmula con ácido hialurónico y colágeno. Anti-edad.",
      price: 28.0,
      currency: "EUR",
      imageUrl:
        "https://placehold.co/400x300/EAEAEA/000000?text=CREMA+DE+NOCHE",
      category: "Belleza",
      stock: 22,
      rating: 4.6,
      isNew: false,
      isDiscounted: false,
    },
    {
      id: 214,
      name: "Set de Brochas de Maquillaje Pro (12 pzas)",
      description: "Cerdas veganas ultra-suaves. Incluye estuche de viaje.",
      price: 45.99,
      currency: "EUR",
      imageUrl:
        "https://placehold.co/400x300/EAEAEA/000000?text=SET+DE+BROCHAS",
      category: "Belleza",
      stock: 12,
      rating: 4.8,
      isNew: true,
      isDiscounted: true,
      oldPrice: 60.0,
    },
    // Libros y Ocio
    {
      id: 215,
      name: "Novela 'El Secreto de la Fuente'",
      description: "Bestseller de misterio. 450 páginas de intriga.",
      price: 15.9,
      currency: "EUR",
      imageUrl:
        "https://placehold.co/400x300/EAEAEA/000000?text=NOVELA+BESTSELLER",
      category: "Libros",
      stock: 150,
      rating: 4.0,
      isNew: false,
      isDiscounted: false,
    },
    {
      id: 216,
      name: "Juego de Mesa 'Colonizadores Espaciales'",
      description: "Estrategia para 2-4 jugadores. Recomendado +12 años.",
      price: 35.5,
      currency: "EUR",
      imageUrl: "https://placehold.co/400x300/EAEAEA/000000?text=JUEGO+DE+MESA",
      category: "Ocio",
      stock: 8,
      rating: 4.4,
      isNew: true,
      isDiscounted: false,
    },
    // Varios / Complementos
    {
      id: 217,
      name: "Botella Termo de Acero Inoxidable (750ml)",
      description:
        "Mantiene bebidas frías 24h y calientes 12h. Tapa antiderrame.",
      price: 22.0,
      currency: "EUR",
      imageUrl: "https://placehold.co/400x300/EAEAEA/000000?text=BOTELLA+TERMO",
      category: "Hogar",
      stock: 0,
      rating: 4.7,
      isNew: false,
      isDiscounted: false,
    },
    {
      id: 218,
      name: "Cargador Rápido de Pared USB-C (65W)",
      description:
        "Carga laptops y móviles a máxima velocidad. Diseño compacto.",
      price: 49.95,
      currency: "EUR",
      imageUrl:
        "https://placehold.co/400x300/EAEAEA/000000?text=CARGADOR+USB-C",
      category: "Electrónica",
      stock: 50,
      rating: 4.6,
      isNew: true,
      isDiscounted: false,
    },
    {
      id: 219,
      name: "Sudadera Básica con Capucha Gris",
      description: "Un clásico atemporal. Algodón de alta calidad. Unisex.",
      price: 45.0,
      currency: "EUR",
      imageUrl: "https://placehold.co/400x300/EAEAEA/000000?text=SUDADERA+GRIS",
      category: "Ropa",
      stock: 120,
      rating: 4.1,
      isNew: false,
      isDiscounted: false,
    },
    {
      id: 220,
      name: "Taza para Viaje con Aislamiento Térmico",
      description: "Perfecta para llevar. Capacidad de 400ml.",
      price: 19.99,
      currency: "EUR",
      imageUrl: "https://placehold.co/400x300/EAEAEA/000000?text=TAZA+VIAJE",
      category: "Cocina",
      stock: 15,
      rating: 4.3,
      isNew: false,
      isDiscounted: true,
      oldPrice: 24.99,
    },
  ],
  totalResults: 20,
  page: 1,
  pageSize: 20,
};

export default extendedMockProductsData;
